version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 10
    groups:
      dotnet:
        patterns:
          - "*"