image:
  - Ubuntu
  - macOS
install:
  - pwsh: |
    if ($isWindows) {
      echo "Do nothing"
    }
    else {
      Invoke-WebRequest "https://dot.net/v1/dotnet-install.sh" -OutFile "./dotnet-install.sh"
      sudo chmod u+x dotnet-install.sh
      if ($isMacOS) {
        sudo ./dotnet-install.sh --install-dir '/usr/local/share/dotnet'
      } else {
        sudo ./dotnet-install.sh --install-dir '/usr/share/dotnet'
      }
    }
build_script:
  - cd scripts
  - cmd: .\benchmark.bat
  - sh: ./benchmark.sh
artifacts:
  - path: scripts/BenchmarkDotNet.Artifacts
    name: Benchmark results