image:
  - Visual Studio 2022
  - Ubuntu
  - macOS
install:
  - sh: wget https://dot.net/v1/dotnet-install.sh
build_script:
  - cd scripts
  - cmd: .\benchmark.bat
  - sh: ./benchmark.sh
artifacts:
  - path: scripts/BenchmarkDotNet.Artifacts
    name: Benchmark results