name: GitHub action build
on: push

jobs:
  Main-build_windows:

    runs-on: windows-latest

    steps:
    - name: GIT checkout
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Run build script
      working-directory: scripts
      run: ./dotnet_build.sh code_coverage