name: GitHub action build
on: push

jobs:
  Main-build_windows:

    runs-on: windows-latest

    steps:
    - name: GIT checkout
      uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test net7.0
      run: dotnet test --configuration Release --no-build --verbosity normal --framework net7.0 --collect:"XPlat Code Coverage;Format=lcov"
    - name: Copy test coverage file
      run: Get-Childitem –Path ".\tests\Fastenshtein.Tests\TestResults\" -Include "coverage.info" -File -Recurse | Move-Item -Destination "coverage.net7.info"
    - name: Test net48
      run: dotnet test --configuration Release --no-build --verbosity normal --framework net48 --collect:"XPlat Code Coverage;Format=lcov"
    - name: Copy test coverage file
      run: Get-Childitem –Path ".\tests\Fastenshtein.Tests\TestResults\" -Include "coverage.info" -File -Recurse | Move-Item -Destination coverage.net48.info
    - name: Upload test coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        format: lcov
        files: coverage.net7.info coverage.net48.info
    - name: Pack
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Fastenshtein.nupkg
        path: src\Fastenshtein\bin\Release\Fastenshtein.*.nupkg
    - name: Run benchmark
      run: .\benchmarks\Fastenshtein.Benchmarking\bin\Release\net7.0\Fastenshtein.Benchmarking.exe
    - name: Upload benchmarks-results to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: benchmarks-results-windows-latest
        path: BenchmarkDotNet.Artifacts


  benchmarks:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: GIT checkout
      uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Run benchmarks script
      run: |
        cd scripts
        ./benchmark.sh
    - name: Upload benchmarks-results to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: benchmarks-results-${{ matrix.os }}
        path: scripts/BenchmarkDotNet.Artifacts