name: GitHub action build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Main-build_windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults /p:CoverletOutputFormat=lcov
    - name: Upload net5.0 unit test code coverage to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: .\tests\Fastenshtein.Tests\TestResults.net5.0.info
    - name: Upload net48 unit test code coverage to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: .\tests\Fastenshtein.Tests\TestResults.net48.info
    - name: Pack
      run: dotnet pack --configuration Release --no-build --no-restore --nologo
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Fastenshtein.nupkg
        path: src\Fastenshtein\bin\Release\Fastenshtein.*.nupkg
    - name: Run benchmark
      run: .\benchmarks\Fastenshtein.Benchmarking\bin\Release\net5.0\Fastenshtein.Benchmarking.exe
    - name: Upload benchmarks-results to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: benchmarks-results-windows-latest
        path: BenchmarkDotNet.Artifacts
        
  benchmarks:
  
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Run benchmarks script
      run: |
        cd scripts
        ./benchmark.sh
    - name: Upload benchmarks-results to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: benchmarks-results-${{ matrix.os }}
        path: scripts/BenchmarkDotNet.Artifacts